SQL implementation
betrybe/eslint-config-trybe pull request #6
Opened 2021-02-22 14:43 UTC by LizzardMedeiros

2021-02-22 16:39 UTC, roziscoding requested changes

2021-03-16 23:32 UTC, roziscoding commented
@LizzardMedeiros temos essa configuração funcionando em algum projeto?
Seria interessante criar uma nova branch na rúbrica de um projeto de SQL e aplicá-la para garantir que esteja funcionando. O que acha?

2021-03-17 11:22 UTC, LizzardMedeiros commented
Não estão, vi que estavam dando falso positivo! Preciso descobrir um jeito do eslint ler arquivos SQL

2022-04-21 20:00 UTC, albertosca commented on packages/sql/package.json
> +    "eslint-plugin-sql": "^1.2.0"
```suggestion
    "eslint": "7.20.0",
    "eslint-plugin-sql": "1.2.0"
```

2022-04-21 20:01 UTC, albertosca approved these changes

2022-04-21 20:04 UTC, albertosca commented
**Para implementar, é preciso ajustar os códigos de SQL da Trybe usando a config nova:**
- [ ] Todos os projetos ativos
- [ ] Todos os códigos de conteúdo
- [ ] Todos os gabaritos
- [ ] Todos os códigos de aula ao vivo.

2022-08-09 19:53 UTC, robertotcestari commented
@betrybe/conteudo-back-end fechando aqui por inatividade. Se fizer sentido, fiquem à vontade em reabrir :)

2022-08-09 19:53 UTC, closed without merging